version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: move-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - mysql-data:/var/lib/mysql
      - ./schema_mysql.sql:/docker-entrypoint-initdb.d/schema_mysql.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5

  postgres:
    image: postgres:13
    container_name: move-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: move-app
    command: ["./wait-for-it.sh", "mysql:3306", "--", "./wait-for-it.sh", "postgres:5432", "--", "python", "app.py"]
    volumes:
      - .:/app
    depends_on:
      - mysql
      - postgres

volumes:
  mysql-data:
  postgres-data:
